In [1]:
from __future__ import print_function
from __future__ import division
from __future__ import absolute_import

In [2]:
import tensorflow as tf

In [9]:
a = tf.constant(32)
b = tf.constant(10)

c = tf.add(a,b)

sess = tf.Session()

print(sess.run(c))

sess.close()

42


In [10]:
print(a)

Tensor("Const_4:0", shape=(), dtype=int32)


In [12]:
mat = tf.constant([[1,0],[0,1]])
sess = tf.Session()

In [13]:
print(sess.run(mat))

[[1 0]
 [0 1]]


In [14]:
my_name_is_hello = tf.constant('Hello', name='Hello')
my_name_is_world = tf.constant('World', name='World')

In [15]:
print("Tensor: {}: {}".format(my_name_is_hello.name, sess.run(my_name_is_hello)))

Tensor: Hello:0: b'Hello'


In [21]:
d = tf.add_n([a,b,b])

e = tf.subtract(a,b)

f = tf.multiply(a,b)

g = tf.divide(a,b)

h = tf.mod(a,b)

print(sess.run([d,e,f,g,h]))

In [43]:
a_float = tf.cast(a, dtype=tf.float32)
b_float = tf.cast(b, dtype=tf.float32)

i = tf.sin(a_float)
j = tf.exp(tf.divide(1.0, a_float))

k = tf.add(i, tf.log(i))

print(sess.run([i, j, k]))

sigmoid = tf.divide(1.0, tf.add(1.0, tf.exp(-b_float)))

print(sess.run(sigmoid))

[0.5514267, 1.0317434, -0.043819606]
0.9999546


In [44]:
mat_a = tf.constant([1,2,3,4])
mat_a = tf.reshape(mat_a,(2,2))

mat_b = tf.constant([1,3,5,7,9,11])
mat_b = tf.reshape(mat_b, (2,3))
vec_a = tf.constant([1,2])

mat_c = tf.matmul(mat_a, mat_b)
mat_d = tf.multiply(mat_a, vec_a)

print(sess.run(mat_a))
print(sess.run(mat_b))
print(sess.run(mat_c))
print(sess.run(mat_d))

[[1 2]
 [3 4]]
[[ 1  3  5]
 [ 7  9 11]]
[[15 21 27]
 [31 45 59]]
[[1 4]
 [3 8]]


In [58]:
zeros = tf.zeros((2,3), dtype=tf.float32)

zeros_like = tf.zeros_like(zeros)

one_like = tf.ones_like(zeros)

fill = tf.fill((2,4),2)

linspace = tf.linspace(1.0, 5.0, 5)

ranger = tf.range(3,18, delta=3)

print('{}:\n{}\n'.format('zeros', sess.run(zeros)))

print('{}:\n{}\n'.format('zeros_like', sess.run(zeros_like)))

print('{}:\n{}\n'.format('ones_like', sess.run(one_like)))

print('{}:\n{}\n'.format('fill', sess.run(fill)))

print('{}:\n{}\n'.format('linspace', sess.run(linspace)))

print('{}:\n{}\n'.format('range', sess.run(ranger)))

zeros:
[[0. 0. 0.]
 [0. 0. 0.]]

zeros_like:
[[0. 0. 0.]
 [0. 0. 0.]]

ones_like:
[[1. 1. 1.]
 [1. 1. 1.]]

fill:
[[2 2 2 2]
 [2 2 2 2]]

linspace:
[1. 2. 3. 4. 5.]

range:
[ 3  6  9 12 15]



In [65]:
#random tensors 
rand_normal = tf.random_normal((), mean=0.0, stddev=1.0, dtype=tf.float32, seed=None)

truncated_normal = tf.truncated_normal((), mean=0.0, stddev=1.0, dtype=tf.float32, seed=None)
#这是一个截断的产生正太分布的函数，就是说产生正太分布的值如果与均值的差值大于两倍的标准差，那就重新生成
rand_uniform = tf.random_uniform((), minval=0.0, maxval=1.0, dtype=tf.float32, seed=None)

for i in range(5):
    print('time: %d' % i)
    print('rand_normal: %.4f' % sess.run(rand_normal))
    print('truncated_normal: %.4f' % sess.run(truncated_normal))
    print('rand_uniform: %.4f' % sess.run(rand_uniform))



time: 0
rand_normal: 0.7877
truncated_normal: 0.1986
rand_uniform: 0.3327
time: 1
rand_normal: -1.1790
truncated_normal: 0.1922
rand_uniform: 0.2007
time: 2
rand_normal: -1.7079
truncated_normal: 1.3522
rand_uniform: 0.5093
time: 3
rand_normal: -0.1419
truncated_normal: 0.8265
rand_uniform: 0.9513
time: 4
rand_normal: -0.1486
truncated_normal: 0.2604
rand_uniform: 0.1754


In [67]:
sess.close()

In [66]:
var_a =tf.Variable(0, dtype=tf.float32)
var_b = tf.Variable([1,2], dtype=tf.float32)
var_w = tf.Variable(tf.zeros((1024, 10)))

sess =tf.InteractiveSession()

init = tf.global_variables_initializer()

sess.run(init)
init.run()

init_ab = tf.variables_initializer([var_a, var_b])

init_ab.run()

var_w.initializer.run()

In [79]:
W = tf.Variable(10)
sess.run(W.initializer)

print(W)
print(sess.run(W))
print(W.eval())

<tf.Variable 'Variable_5:0' shape=() dtype=int32_ref>
10
10


In [84]:
W.assign(100)
W.initializer.run()
print(W.eval(sess))

assign_op = W.assign(100)
W.initializer.run()
assign_op.eval()
print(W.eval())

10
100


In [87]:
assign_add = W.assign_add(10)
assign_sub = W.assign_sub(2)
W.initializer.run()

print(assign_add.eval())
print(assign_sub.eval())
print(assign_sub.eval())
print(W.eval())

20
18
16
16


In [91]:
# tensor 名称域 name_scope , variable_scope
with tf.name_scope('name_scope'):
    var_a = tf.Variable(0, dtype=tf.int32)
    var_b = tf.Variable([1,2], dtype=tf.float32)

with tf.variable_scope('var_scope'):
    var_c = tf.Variable(0, dtype=tf.int32)
    var_d = tf.Variable([1,2], dtype=tf.float32)

print(var_a.name)
print(var_b.name)
print(var_c.name)
print(var_d.name)

name_scope_1/Variable:0
name_scope_1/Variable_1:0
var_scope_1/Variable:0
var_scope_1/Variable_1:0


In [96]:
#placeholders  占位符
a =tf.placeholder(tf.float32, shape=[3])
b = tf.placeholder(tf.bool, shape=[1,2])

print(sess.run(a, feed_dict={a: [1,2,3]}))
print(sess.run([a,b], feed_dict={a:[1,2,3], b:[[True,False]]}))

[1. 2. 3.]
[array([1., 2., 3.], dtype=float32), array([[ True, False]])]


In [97]:
a = tf.placeholder(tf.float32)
square = tf.square(a)

In [101]:
for i in [1,2,4,8]:
    print(square.eval(feed_dict={a:i}))

1.0
4.0
16.0
64.0


In [104]:
#tf.Graph
g = tf.get_default_graph()

print(g)

for op in g.get_operations():
    print(op.name)

In [110]:
#what_is_this = g.get_tensor_by_name('Hello:0')
#print(what_is_this.eval())
#sess.close()

In [116]:
tf.reset_default_graph()

In [117]:
g1 = tf.Graph()
print('g1', g1)

print('default_graph', tf.get_default_graph())
g1.as_default()
print('default_graph', tf.get_default_graph())

g1 <tensorflow.python.framework.ops.Graph object at 0x7fefc84d77f0>


In [119]:
a1 = tf.constant(32, name='a1')

In [120]:
with g1.as_default():
    a2 = tf.constant(32, name='a2')

In [121]:
print('a.graph: ', a.graph)
print('a1.graph:', a1.graph)
print('a2.graph:', a2.graph)

a.graph:  <tensorflow.python.framework.ops.Graph object at 0x7feffeaf74a8>
a1.graph: <tensorflow.python.framework.ops.Graph object at 0x7fefc84d7dd8>
a2.graph: <tensorflow.python.framework.ops.Graph object at 0x7fefc84d77f0>
