In [9]:
import tensorflow as tf

voc_size = 2
embed_size = 5
embeddings = tf.Variable(tf.random_uniform([voc_size, embed_size], -1.0,-1.0))
embed = tf.nn.embedding_lookup(embeddings,[1,0])
sess = tf.InteractiveSession()

sess.run(tf.global_variables_initializer())
print(sess.run(embeddings))
print(sess.run(embed))

[[-1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1.]]
[[-1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1.]]


/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py:1702: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '
